name: SeasonCycle
version: 1.0
author: HardBuckaroo
main: me.hardbuckaroo.seasoncycle.SeasonCycle
api-version: 1.20
load: STARTUP
commands:
  seasonadvance:
    description: Advances forward 1-3 seasons.
    usage: /SeasonAdvance 1
    permission: op
  getseason:
    description: Prints the current season and year.
    usage: /getseason
  mapchunk:
    description: Maps the current chunk in OriginalBiomes.csv
    usage: /mapchunk
    permission: op
  setseason:
    description: Sets season and year to the specified values.
    usage: /setseason [season] [year] or /setseason [season]
    permission: op
